### PR TITLE
Minor Webpack related tweak for mount function registration 

### PR DESCRIPTION
**Pull request by crafterm**
Hi Philip,

Thanks heaps for your help with web pack support and 0.1.3 - I had to make the following change in this PR to get it all working, otherwise the mount function was not being registered/defined properly.

Also, in my case too I had to use:

```
<react-component></react-component>
```

rather than just:

```
<react-component />
```

otherwise the markup was getting quite confused - not sure about that one but perhaps you might have some insights as to why this might be the case?

Hope you agree with the changes, please let me know if it needs to be done a different way, happy to help.

Cheers,

Marcus

### CODE REVIEW

**Comment by ph101pp** [comment]
Hi Markus, 

Thanks for the PR! 
Do you have a minimal example of the problem, that you could send me or add to your fork? Would love to have a look.

Thanks 
Philipp

**Comment by crafterm** [comment]
Hi Philipp,

Sure thing mate, I’ve just added a webpack based example to the PR, this is using the latest released version of react-mount, not the bundled repository version that I changed so that you can see the error I’m seeing.

If you open the index.html, you’ll (hopefully) see what I see - which is the component not mounted, and 'Uncaught TypeError: React.mount is not a function’ in the chrome console.

In my case, I had to update both the test and assignment of window.React to get it to work, otherwise, errors in either case.

Hope this helps demonstrate the problem - I’ve checked in the bundle.js and bundle.js.map generated by webpack, so that you don’t have to recreate it but, if you’d like to, the command to re-run that I was using is at the top of index.js.

Let me know if I can be of any more help.

Cheers,

Marcus

**Comment by crafterm** [comment]
Hi Philipp,

Hope all is going well mate and the example helps demonstrate the error message I was receiving - have had great success all week using react-mount with webpack and the patch.

Perhaps if you're not keen on always attaching to the required React variable, we could combine approaches and use the window.React if its defined, i.e.:

```
if (typeof window.React === "object") {
    window.React.mount = mount
} else if (typeof React === "object") {
    React.mount = mount
}
```

I think the main problem is that window.React isn't exposed in webpack by default, and hence needs to fall back to the require'd React reference that brings it into scope.

Let me know if that helps and if I can help resolve it with any other approach mate?

Talk soon.

Cheers,

Marcus

**Comment by ph101pp** [comment]
Marcus, 

Thanks a lot for your example! I finally had time to take a look:

The intended use case for defining the `mount` function on `window.React` is for people who don't use commonJS/AMD bundler like webpack or browserify but implement react-mount via script tag in html.
One of the reasons to use the commonJS or AMD pattern and _require_ dependencies is to avoid properties on the global namespace. 

In my opinion, since you're using the commonJS pattern and webpack, react-mount is behaving correctly in not defining a property in the global namespace.

There are two possible solutions for your problem without changing react-mount:

---

**Solution 1:** _(I would highly recommend this one)_
Just use the _required_ react-mount instance within your module. There is no need to expose it to the global namespace.

_index.js:_

```
// no need to load react, react-mount takes care of this.
// import React from 'react'

// and no need to expose anything here
// require('expose?React!react')
// require('expose?ExampleApplication!./example')


// Just require / import react-mount and the component and mount the component:

import mount from 'react-mount'
import ExampleApplication from './example'

mount({
  "example-application" : ExampleApplication
});

```

you can then delete the whole `<!-- mount components -->` script tag in your html

---

**Solution 2:**
If for some reason you need React and reactMount on the global namespace. You can expose the mount function yourself:

_index.js:_

```
// these shouldn't be needed
// import mount from 'react-mount'
// import React from 'react'

require('expose?React!react')
require('expose?ExampleApplication!./example')

// Expose react-mount as ReactMount
require('expose?ReactMount!react-mount')

```

Then you can use it in your html:

```
<script>
   // wait for JSXTransformer to be done. (Only necessary if components are not precompiled.
   window.addEventListener( "DOMContentLoaded", function(){
     ReactMount({
       "example-application" : ExampleApplication
     });
   });
</script>
```

---

I hope this is help full and solves your problem. 
Let me know if you still have questions.

Thanks for contributing and using `react-mount`

Cheers Philipp

**Comment by crafterm** [comment]
Hi Philipp,

Very late response but wanted to thank you for your detailed response and also let you know that the second option below worked fine for our case and suits us perfectly.

Thanks for describing it all in detail and going through it in depth.

Cheers mate.

Marcus

**Pull request closed without merging**
